# Default application configuration that all configurations inherit from.

scss_files: './Styles/**/*.scss'

exclude:
  - './Styles/OOLess/bootstrap/*'
  - './Styles/lib/*'
  - './Styles/OOCss/**/*-sprite.scss'
  - './Styles/less/components/_normalize.scss'

linters:
  BorderZero:
    enabled: true

  CapitalizationInSelector:
    enabled: true

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: true
    exclude:
      - './Styles/OOLess/**'
      - './Styles/less/**'

  Comment:
    enabled: true
    exclude:
      - './Styles/OOLess/**'
      - './Styles/less/**'

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true
    severity: error

  EmptyLineBetweenBlocks:
    enabled: true
    exclude:
      - './Styles/OOLess/**'
      - './Styles/less/**'
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true
    severity: error

  FinalNewline:
    enabled: true
    present: true

  ImportantRule:
    enabled: true
    severity: warning
    exclude:
      - './Styles/OOLess/**'
      - './Styles/less/**'

  IdSelector:
    enabled: true
    severity: error
    exclude:
      - './Styles/OOLess/**'
      - './Styles/less/**'

  HexLength:
    enabled: true
    style: long
    exclude:
      - './Styles/OOLess/**'
      - './Styles/less/**'

  HexNotation:
    enabled: true
    style: lowercase
    exclude:
      - './Styles/OOLess/**'
      - './Styles/less/**'

  HexValidation:
    enabled: true

  IdWithExtraneousSelector:
    enabled: true

  ImportPath:
    enabled: true
    severity: warning

  Indentation:
    enabled: true
    width: 2
    severity: warning

  LeadingZero:
    enabled: false

  MergeableSelector:
    enabled: true
    force_nesting: true
    exclude:
      - './Styles/OOLess/**'
      - './Styles/less/**'

  NameFormat:
    enabled: true
    convention: hyphenated_lowercase
    exclude:
      - './Styles/OOLess/**'
      - './Styles/less/**'

  NestingDepth:
    enabled: true
    max_depth: 5

  QualifyingElement:
    enabled: true
    exclude:
      - './Styles/OOLess/**'
      - './Styles/less/**'


  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase
    exclude:
      - './Styles/OOLess/**'
      - './Styles/less/**'

  SingleLinePerProperty:
    enabled: true

  PlaceholderInExtend:
    enabled: false

  PropertySortOrder:
    enabled: true

  PropertySpelling:
    enabled: true
    extra_properties: []

  SelectorDepth:
    enabled: true
    max_depth: 5

  Shorthand:
    enabled: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: false

  TrailingSemicolon:
    enabled: true
    severity: error

  # @todo: add font-size and font-family to this
  VariableForProperty:
    enabled: true
    severity: error
    properties:
      - z-index
    exclude:
      - './Styles/OOLess/**'
      - './Styles/less/**'

  VendorPrefix:
    enabled: true
    exclude:
      - './Styles/OOLess/**'
      - './Styles/less/**'

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true
    exclude:
      - './Styles/OOLess/**'
      - './Styles/less/**'

  UrlQuotes:
    enabled: true

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false
