# Default application configuration that all configurations inherit from.

scss_files: './Styles/**/*.scss'

exclude:

linters:
  BorderZero:
    enabled: true

  CapitalizationInSelector:
    enabled: true

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: true

  Comment:
    enabled: true

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true
    severity: error

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true
    severity: error

  FinalNewline:
    enabled: true
    present: true

  ImportantRule:
    enabled: true
    severity: warning

  IdSelector:
    enabled: true
    severity: error

  HexLength:
    enabled: true
    style: long

  HexNotation:
    enabled: true
    style: lowercase

  HexValidation:
    enabled: true

  IdWithExtraneousSelector:
    enabled: true

  ImportPath:
    enabled: true
    severity: warning

  Indentation:
    enabled: true
    width: 2
    severity: warning

  LeadingZero:
    enabled: false

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    convention: hyphenated_lowercase

  NestingDepth:
    enabled: true
    max_depth: 5

  QualifyingElement:
    enabled: true

  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase

  SingleLinePerProperty:
    enabled: true

  PlaceholderInExtend:
    enabled: false

  PropertySortOrder:
    enabled: true

  PropertySpelling:
    enabled: true
    extra_properties: []

  SelectorDepth:
    enabled: true
    max_depth: 5

  Shorthand:
    enabled: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: false

  TrailingSemicolon:
    enabled: true
    severity: error

  VendorPrefix:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false
